# Generated by Django 4.2.4 on 2024-04-09 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='SO.profile'),
        ),
        migrations.AlterField(
            model_name='reactiontoquestion',
            name='user_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_like', to='SO.profile'),
        ),
    ]
