# Generated by Django 4.2.4 on 2024-04-09 19:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('SO', '0003_alter_answer_ans_question_alter_answer_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswernManager',
        ),
        migrations.DeleteModel(
            name='QuestionManager',
        ),
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
