# Generated by Django 4.2.7 on 2024-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SO', '0004_delete_answernmanager_delete_questionmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rayting',
            field=models.IntegerField(default=0),
        ),
    ]
