# Generated by Django 4.2.7 on 2024-05-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SO', '0005_profile_rayting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rayting',
        ),
    ]
